// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // ═══════════════════════════════════════════════════════════════
  // QA sidebar — narrow, role-focused
  // Pinned to ~12 modules QA actually touches.
  // The other 30+ modules are reachable via the dev sidebar.
  // ═══════════════════════════════════════════════════════════════
  qaSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Start here',
    },
    {
      type: 'doc',
      id: 'quality/glossary',
      label: '📖 Glossary',
    },
    {
      type: 'category',
      label: '👤 Roles',
      collapsed: true,
      items: [
        'roles/admin',
        'roles/manager',
        'roles/agent',
        'roles/supervisor',
        'roles/cashier',
        'roles/expeditor',
      ],
    },
    {
      type: 'doc',
      id: 'quality/page-to-module-map',
      label: '🗺️ Page-to-module map',
    },

    {
      type: 'category',
      label: '📘 QA workflow guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '📦 Orders',
          collapsed: true,
          link: { type: 'doc', id: 'quality/orders/index' },
          items: [
            'quality/orders/create-order-web',
            'quality/orders/create-order-mobile',
            'quality/orders/status-transitions',
            'quality/orders/partial-defect',
            'quality/orders/whole-return',
            'quality/orders/edit-order',
            'quality/orders/mobile-payment',
            'quality/orders/discounts',
            'quality/orders/bonuses',
            'quality/orders/cis-code-check',
            'quality/orders/order-list-and-history',
          ],
        },
        {
          type: 'category',
          label: '👥 Team',
          collapsed: true,
          link: { type: 'doc', id: 'quality/team/index' },
          items: [
            'quality/team/role-agent',
            'quality/team/role-supervisor',
            'quality/team/role-expeditor',
            'quality/team/create-edit-agent',
            'quality/team/create-edit-supervisor',
            'quality/team/create-edit-expeditor',
            'quality/team/agents-packet',
            'quality/team/expeditor-packet',
            'quality/team/kpi-setup-and-views',
            'quality/team/tasks',
            'quality/team/product-distribution',
          ],
        },
        {
          type: 'category',
          label: '👤 Clients',
          collapsed: true,
          link: { type: 'doc', id: 'quality/clients/index' },
          items: [
            'quality/clients/create-edit-client',
            'quality/clients/mobile-client-creation',
            'quality/clients/verification',
            'quality/clients/categorisation',
            'quality/clients/bulk-import',
            'quality/clients/duplicate-merge',
          ],
        },
        {
          type: 'category',
          label: '💰 Finans (ledger)',
          collapsed: true,
          link: { type: 'doc', id: 'quality/finans/index' },
          items: [
            'quality/finans/client-debt-view',
            'quality/finans/transaction-types',
            'quality/finans/manual-correction',
            'quality/finans/settlement',
            'quality/finans/multi-currency',
            'quality/finans/cashbox-balance',
          ],
        },
        {
          type: 'category',
          label: '🏬 Stock & Warehouses',
          collapsed: true,
          link: { type: 'doc', id: 'quality/stock/index' },
          items: [
            'quality/stock/store-crud',
            'quality/stock/stock-balance-view',
            'quality/stock/stock-receipt',
            'quality/stock/stock-transfer',
            'quality/stock/defect-and-van-stock',
            'quality/stock/inventory-and-correction',
          ],
        },
        {
          type: 'category',
          label: '⚙️ Settings',
          collapsed: true,
          link: { type: 'doc', id: 'quality/settings/index' },
          items: [
            'quality/settings/cashbox-management',
            'quality/settings/price-types',
            'quality/settings/trade-and-channel',
            'quality/settings/rbac-and-users',
            'quality/settings/bonus-rules',
            'quality/settings/discount-rules',
            'quality/settings/server-toggles-and-period-close',
          ],
        },
        {
          type: 'category',
          label: '💳 Payment & cashbox flows',
          collapsed: true,
          link: { type: 'doc', id: 'quality/payment/index' },
          items: [
            'quality/payment/payment-approval',
            'quality/payment/expenses-and-pnl',
            'quality/payment/supplier-finance',
          ],
        },
        {
          type: 'category',
          label: '📈 Reports',
          collapsed: true,
          link: { type: 'doc', id: 'quality/report/index' },
          items: [
            'quality/report/report-agent',
            'quality/report/report-customer',
            'quality/report/report-volume-sku',
            'quality/report/report-expeditor',
            'quality/report/report-visit',
          ],
        },
        {
          type: 'category',
          label: '🔍 Audit (v1 + v2)',
          collapsed: true,
          link: { type: 'doc', id: 'quality/audit/index' },
          items: [
            'quality/audit/visit-audit',
            'quality/audit/facing-and-sku',
            'quality/audit/photo-reports',
            'quality/audit/audit-settings',
          ],
        },
        {
          type: 'category',
          label: '🏷️ Markirovka (CIS)',
          collapsed: true,
          link: { type: 'doc', id: 'quality/markirovka/index' },
          items: [
            'quality/markirovka/incoming-invoices',
            'quality/markirovka/outgoing-invoices',
          ],
        },
        {
          type: 'category',
          label: '📱 Mobile (GPS / sync / SMS)',
          collapsed: true,
          link: { type: 'doc', id: 'quality/mobile/index' },
          items: [
            'quality/mobile/gps-tracking',
            'quality/mobile/sync-flow',
            'quality/mobile/sms-broadcast',
            'quality/mobile/notifications',
          ],
        },
        {
          type: 'category',
          label: '🔌 Integrations & B2B',
          collapsed: true,
          link: { type: 'doc', id: 'quality/integrations/index' },
          items: [
            'quality/integrations/online-orders',
            'quality/integrations/online-contacts',
            'quality/integrations/faktura-uz',
            'quality/integrations/idokon-pos',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: '📌 Modules QA touches often',
      collapsed: false,
      items: [
        'modules/orders',
        'modules/agents',
        'modules/clients',
        'modules/stock',
        'modules/payment',
        'modules/finans',
        'modules/audit-adt',
        'modules/dashboard',
        'modules/report',
        'modules/sync',
        'modules/onlineOrder',
        'modules/integration',
      ],
    },

    {
      type: 'category',
      label: '📘 Tutorials',
      collapsed: false,
      items: [
        'tutorials/create-order-web',
        'tutorials/create-order-mobile',
        'tutorials/register-payment',
        'tutorials/approve-payment-as-cashier',
        'tutorials/run-kpi-report',
        'tutorials/setup-agent',
        'tutorials/configure-markirovka',
        'tutorials/bulk-import-clients',
        'tutorials/set-up-online-portal',
        'tutorials/daily-stock-reconciliation',
      ],
    },

    {
      type: 'category',
      label: '🌐 sd-cs reports (HQ)',
      collapsed: true,
      link: { type: 'doc', id: 'sd-cs/workflows/index' },
      items: [
        'sd-cs/workflows/report-sale',
        'sd-cs/workflows/report-agent',
        'sd-cs/workflows/report-debt',
        'sd-cs/workflows/report-plan',
        'sd-cs/workflows/report-inventory',
        'sd-cs/workflows/pivot-akb',
      ],
    },

    {
      type: 'category',
      label: '💳 sd-billing flows',
      collapsed: true,
      link: { type: 'doc', id: 'sd-billing/workflows/index' },
      items: [
        'sd-billing/workflows/api-click',
        'sd-billing/workflows/operation-payment',
        'sd-billing/workflows/operation-subscription',
      ],
    },

    {
      type: 'category',
      label: '🔧 Reference',
      collapsed: true,
      items: [
        'quality/testing',
        'troubleshooting',
        'changelog',
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════
  // Developer sidebar — full surface across all three projects
  // (QA Test Guides removed — they live in qaSidebar now)
  // ═══════════════════════════════════════════════════════════════
  developerSidebar: [
    'intro',
    'ecosystem',
    {
      type: 'category',
      label: '💡 Concepts',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
      ],
    },
    {
      type: 'category',
      label: '👤 Roles',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'roles' },
      ],
    },
    {
      type: 'category',
      label: '🔀 Cross-module flows',
      collapsed: false,
      items: [
        'flows/order-end-to-end',
        'flows/online-order-fulfillment',
        'flows/visit-to-kpi',
        'flows/period-close',
        'flows/mobile-sync-conflict',
        'flows/license-tenant-lifecycle',
      ],
    },
    {
      type: 'category',
      label: '🗺️ Diagram gallery',
      collapsed: true,
      link: { type: 'doc', id: 'diagrams/index' },
      items: [
        'diagrams/ecosystem',
        'diagrams/sd-main-system',
        'diagrams/sd-main-features',
        'diagrams/sd-cs',
        'diagrams/sd-billing',
        'diagrams/data',
        'diagrams/workflows',
      ],
    },

    {
      type: 'category',
      label: '📘 Tutorials',
      collapsed: false,
      items: [
        'tutorials/create-order-web',
        'tutorials/create-order-mobile',
        'tutorials/register-payment',
        'tutorials/approve-payment-as-cashier',
        'tutorials/run-kpi-report',
        'tutorials/setup-agent',
        'tutorials/configure-markirovka',
        'tutorials/bulk-import-clients',
        'tutorials/set-up-online-portal',
        'tutorials/daily-stock-reconciliation',
      ],
    },

    // ─── 1. sd-main · Dealer CRM ───────────────────────────────
    {
      type: 'category',
      label: '🏢 sd-main · Dealer CRM',
      collapsed: false,
      link: { type: 'doc', id: 'sd-main/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-main-system-architecture',
          collapsed: true,
          items: [
            'architecture/overview',
            'architecture/tech-stack',
            'architecture/multi-tenancy',
            'architecture/caching',
            'architecture/jobs-and-scheduling',
            'project/structure',
            'project/configuration',
            'project/conventions',
            'project/local-setup',
            'project/docker',
            'security/auth-and-roles',
            'security/rbac',
            'security/sessions',
            'security/data-isolation',
            'security/sd-main-landmines',
            'architecture/diagram-conventions',
            'devops/deployment',
            'devops/docker-compose',
            'devops/nginx',
            'devops/monitoring-logging',
            'devops/backup-and-restore',
            'devops/scaling',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-main-workflows',
          collapsed: true,
          items: [
            'modules/overview',
            {
              type: 'category',
              label: '🖼️ UI page reference',
              key: 'sd-main-ui-pages',
              collapsed: true,
              link: { type: 'doc', id: 'ui/pages/index' },
              items: [
                { type: 'autogenerated', dirName: 'ui/pages' },
              ],
            },
            'modules/orders',
            'modules/clients',
            'modules/agents',
            'modules/warehouse',
            'modules/inventory',
            'modules/stock',
            'modules/store',
            'modules/finans',
            'modules/payment',
            'modules/pay',
            'modules/audit-adt',
            'modules/doctor',
            'modules/gps',
            'modules/gps2',
            'modules/gps3',
            'modules/integration',
            'modules/markirovka',
            'modules/neakb',
            'modules/onlineOrder',
            'modules/partners',
            'modules/planning',
            'modules/rating',
            'modules/sms',
            'modules/dashboard',
            'modules/report',
            'modules/settings',
            'modules/access',
            'modules/staff',
            'modules/manager',
            'modules/settings-access-staff',
            'modules/sync',
            'modules/team',
            'modules/vs',
            'api/overview',
            'api/authentication',
            'api/api-v1',
            'api/api-v2',
            {
              type: 'category',
              label: 'API v3 — Mobile agent',
              key: 'api-v3-mobile',
              collapsed: true,
              link: { type: 'doc', id: 'api/api-v3-mobile/index' },
              items: [{ type: 'autogenerated', dirName: 'api/api-v3-mobile' }],
            },
            {
              type: 'category',
              label: 'API v4 — Online / B2B',
              key: 'api-v4-online',
              collapsed: true,
              link: { type: 'doc', id: 'api/api-v4-online/index' },
              items: [{ type: 'autogenerated', dirName: 'api/api-v4-online' }],
            },
            'api/error-codes',
            'api/webhooks',
            'integrations/overview',
            'integrations/1c-esale',
            'integrations/didox',
            'integrations/faktura-uz',
            'integrations/smartup',
            'integrations/telegram',
            'integrations/fcm',
            'integrations/sms',
            'integrations/gps',
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-main-data-schemes',
          collapsed: true,
          items: [
            'data/overview',
            'data/erd',
            'data/erd-real',
            'data/schema-reference',
            'data/core-entities',
            'data/conventions',
            'data/migrations',
            'data/sd-billing/schema',
            'data/sd-cs/schema',
            'data/deprecated',
          ],
        },
      ],
    },

    // ─── 2. sd-cs · HQ Country Sales ───────────────────────────
    {
      type: 'category',
      label: '🌐 sd-cs · HQ Country Sales',
      collapsed: true,
      link: { type: 'doc', id: 'sd-cs/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-cs-system-architecture',
          collapsed: true,
          items: [
            'sd-cs/architecture',
            'sd-cs/multi-db',
            'sd-cs/local-setup',
            'sd-cs/sd-components',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-cs-workflows',
          collapsed: true,
          items: [
            'sd-cs/modules',
            {
              type: 'category',
              label: 'Module deep dives',
              key: 'sd-cs-module-deep-dives',
              collapsed: true,
              items: [
                'sd-cs/modules/api',
                'sd-cs/modules/api3',
                'sd-cs/modules/user',
                'sd-cs/modules/directory',
                'sd-cs/modules/dashboard',
                'sd-cs/modules/pivot',
                'sd-cs/modules/report',
              ],
            },
            'sd-cs/sd-main-integration',
            'sd-cs/reports-pivots',
            {
              type: 'category',
              label: 'Feature workflows',
              key: 'sd-cs-feature-workflows',
              collapsed: true,
              link: { type: 'doc', id: 'sd-cs/workflows/index' },
              items: [
                'sd-cs/workflows/report-sale',
                'sd-cs/workflows/report-agent',
                'sd-cs/workflows/report-debt',
                'sd-cs/workflows/report-plan',
                'sd-cs/workflows/report-inventory',
                'sd-cs/workflows/report-kpi',
                'sd-cs/workflows/report-photo',
                'sd-cs/workflows/report-sell',
                'sd-cs/workflows/pivot-akb',
                'sd-cs/workflows/pivot-inventory',
                'sd-cs/workflows/pivot-rfm',
                'sd-cs/workflows/style',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-cs-data-schemes',
          collapsed: true,
          items: [
            'sd-cs/data-schemes',
          ],
        },
      ],
    },

    // ─── 3. sd-billing · Subscriptions & licensing ─────────────
    {
      type: 'category',
      label: '💳 sd-billing · Subscriptions',
      collapsed: true,
      link: { type: 'doc', id: 'sd-billing/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-billing-system-architecture',
          collapsed: true,
          items: [
            'sd-billing/modules',
            {
              type: 'category',
              label: 'Module deep dives',
              key: 'sd-billing-module-deep-dives',
              collapsed: true,
              items: [
                'sd-billing/modules/access',
                'sd-billing/modules/dbservice',
                'sd-billing/modules/directory',
                'sd-billing/modules/sms',
                'sd-billing/modules/api',
                'sd-billing/modules/notification',
                'sd-billing/modules/partner',
                'sd-billing/modules/bonus',
                'sd-billing/modules/cashbox',
                'sd-billing/modules/dashboard',
                'sd-billing/modules/operation',
                'sd-billing/modules/report',
                'sd-billing/modules/setting',
              ],
            },
            'sd-billing/auth-and-access',
            'sd-billing/local-setup',
            'sd-billing/security-landmines',
            'sd-billing/api-reference',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-billing-workflows',
          collapsed: true,
          items: [
            'sd-billing/subscription-flow',
            'sd-billing/cron-and-settlement',
            'sd-billing/payment-gateways',
            'sd-billing/integration',
            'sd-billing/notifications',
            {
              type: 'category',
              label: 'Feature workflows',
              key: 'sd-billing-feature-workflows',
              collapsed: true,
              link: { type: 'doc', id: 'sd-billing/workflows/index' },
              items: [
                'sd-billing/workflows/api-click',
                'sd-billing/workflows/operation-payment',
                'sd-billing/workflows/operation-subscription',
                'sd-billing/workflows/operation-package',
                'sd-billing/workflows/operation-tariff',
                'sd-billing/workflows/operation-blacklist',
                'sd-billing/workflows/operation-notification-rules',
                'sd-billing/workflows/license-push',
                'sd-billing/workflows/style',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-billing-data-schemes',
          collapsed: true,
          items: [
            'sd-billing/domain-model',
            'sd-billing/data-scheme',
            'sd-billing/balance-and-money-math',
          ],
        },
      ],
    },

    // ─── Cross-cutting reference ───────────────────────────────
    {
      type: 'category',
      label: '🔧 Reference & cross-cutting',
      collapsed: true,
      key: 'reference-cross-cutting',
      items: [
        {
          type: 'category',
          label: '🔐 RBAC reference',
          collapsed: true,
          items: [
            'security/rbac-matrix',
            'security/operations-catalog',
            'security/sd-billing-rbac',
            'security/sd-cs-rbac',
          ],
        },
        {
          type: 'category',
          label: '⚙️ Settings catalog',
          collapsed: true,
          link: { type: 'doc', id: 'reference/settings/index' },
          items: [
            'reference/settings/sd-main-server-settings',
            'reference/settings/sd-main-tenant-settings',
            'reference/settings/sd-billing-settings',
            'reference/settings/sd-cs-settings',
          ],
        },
        'architecture/cross-project-integration',
        'architecture/diagrams',
        'security/overview',
        'team/index',
        'team/onboarding',
        'team/qa',
        'team/pm',
        'team/workflow-design',
        'team/rag-indexing',
        'team/contributing',
        'team/style-guide',
        'team/translating',
        'team/screenshot-pipeline',
        'quality/testing',
        'quality/coding-standards',
        'quality/contribution',
        'quality/release-process',
        'adr/index',
        'adr/yii1-stay',
        'adr/multi-tenant-db-per-customer',
        'adr/redis-three-databases',
        'adr/api-versioning',
        'billing/overview',
        'diagrams-inventory',
      ],
    },

    'troubleshooting',
    'changelog',
  ],
};

module.exports = sidebars;
